// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/private/workbook": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Create new workbook",
                "parameters": [
                    {
                        "description": "parameter to create new workbook",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.WorkbookAddParameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlerhelper.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/v1/private/workbook/search": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Find workbooks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.WorkbookSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/v1/private/workbook/{workbookID}": {
            "put": {
                "description": "update the workbook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "private workbook"
                ],
                "summary": "Update the workbook",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workbook ID",
                        "name": "workbookID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "parameter to update the workbook",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.WorkbookUpdateParameter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlerhelper.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/v1/study/workbook/{workbookID}/study_type/{studyType}": {
            "get": {
                "description": "find results of workbook",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "study"
                ],
                "summary": "Find the recordbook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workbook ID",
                        "name": "workbookID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Study type",
                        "name": "studyType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.StudyRecords"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/v1/study/workbook/{workbookID}/study_type/{studyType}/completion_rate": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "study"
                ],
                "summary": "Get the completion rate of the workbook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workbook ID",
                        "name": "workbookID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Study type",
                        "name": "studyType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.StudyRecord": {
            "type": "object",
            "properties": {
                "lastAnsweredAt": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "memorized": {
                    "type": "boolean"
                },
                "problemId": {
                    "type": "integer"
                },
                "resultPrev1": {
                    "type": "boolean"
                }
            }
        },
        "entity.StudyRecords": {
            "type": "object",
            "properties": {
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.StudyRecord"
                    }
                }
            }
        },
        "entity.WorkbookAddParameter": {
            "type": "object",
            "required": [
                "name",
                "problemType"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "problemType": {
                    "type": "string"
                },
                "questionText": {
                    "type": "string"
                }
            }
        },
        "entity.WorkbookResponseHTTPEntity": {
            "type": "object",
            "required": [
                "lang2",
                "name",
                "problemType",
                "version"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer",
                    "minimum": 0
                },
                "id": {
                    "type": "integer",
                    "minimum": 0
                },
                "lang2": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "problemType": {
                    "type": "string"
                },
                "questionText": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer",
                    "minimum": 0
                },
                "version": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "entity.WorkbookSearchResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.WorkbookResponseHTTPEntity"
                    }
                },
                "totalCount": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "entity.WorkbookUpdateParameter": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "questionText": {
                    "type": "string"
                }
            }
        },
        "handlerhelper.IDResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
