---
version: '3'
services:
  dev-mysql:
    image: mysql:8.0.27
    container_name: dev-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - "./mysql-data:/var/lib/mysql"
  dev-translator-mysql:
    image: mysql:8.0.27
    container_name: dev-translator-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3316:3306
    volumes:
      - "./mysql-data-translator:/var/lib/mysql"
  dev-tatoeba-mysql:
    image: mysql:8.0.27
    container_name: dev-tatoeba-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3326:3306
    volumes:
      - "./mysql-data-tatoeba:/var/lib/mysql"
  dev-synthesizer-mysql:
    image: mysql:8.0.27
    container_name: dev-synthesizer-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3336:3306
    volumes:
      - "./mysql-data-synthesizer:/var/lib/mysql"

  dev-jaeger:
    image: jaegertracing/all-in-one:1.33.0
    container_name: dev-jaeger
    ports:
      - 14268:14268
      - 16686:16686
