---
steps:
  # - name: 'gcr.io/cloud-builders/bazel'
  #   entrypoint: 'bazel'
  #   args: ['version']
  # - name: 'gcr.io/cloud-builders/bazel'
  #   entrypoint: 'bazel'
  #   args: ['build', '//...']

  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - -c
      - |
        git diff --name-only | grep cocotola-api
        diff_cocotola=$?
        echo $diff_cocotola

  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - -c
      - |
        git diff --name-only | grep cocotola-synthesizer-api
        diff_cocotola_synthesizer=$?
        echo synthe=$diff_cocotola_synthesizer
        echo cocotola=$diff_cocotola

  # synthesizer
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/cocotola-synthesizer-api:latest || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    id: "docker build synthesizer"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA", "--cache-from", "gcr.io/$PROJECT_ID/cocotola-synthesizer-api:latest","./cocotola-synthesizer-api"]

  - name: "gcr.io/cloud-builders/docker"
    id: "docker tag synthesizer"
    args: ["tag", "gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA", "gcr.io/$PROJECT_ID/cocotola-synthesizer-api:latest"]

  - name: "gcr.io/cloud-builders/docker"
    id: "docker push synthesizer"
    args: ["push", "gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA"]

  # translator
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/cocotola-translator-api:latest || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    id: "docker build translator"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA", "--cache-from", "gcr.io/$PROJECT_ID/cocotola-translator-api:latest","./cocotola-translator-api"]

  - name: "gcr.io/cloud-builders/docker"
    id: "docker tag translator"
    args: ["tag", "gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA", "gcr.io/$PROJECT_ID/cocotola-translator-api:latest"]

  - name: "gcr.io/cloud-builders/docker"
    id: "docker push translator"
    args: ["push", "gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA"]

  # tatoeba
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/cocotola-tatoeba-api:latest || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    id: "docker build tatoeba"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA", "--cache-from", "gcr.io/$PROJECT_ID/cocotola-tatoeba-api:latest","./cocotola-tatoeba-api"]

  - name: "gcr.io/cloud-builders/docker"
    id: "docker tag tatoeba"
    args: ["tag", "gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA", "gcr.io/$PROJECT_ID/cocotola-tatoeba-api:latest"]

  - name: "gcr.io/cloud-builders/docker"
    id: "docker push tatoeba"
    args: ["push", "gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA"]

  # cocotola
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/cocotola-api:latest || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    id: "docker build cocotola"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA", "--cache-from", "gcr.io/$PROJECT_ID/cocotola-api:latest","./cocotola-api"]

  - name: "gcr.io/cloud-builders/docker"
    id: "docker tag cocotola"
    args: ["tag", "gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA", "gcr.io/$PROJECT_ID/cocotola-api:latest"]

  - name: "gcr.io/cloud-builders/docker"
    id: "docker push cocotola"
    args: ["push", "gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA"]

  # common
  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - -c
      - |
        git config --global user.email "cloudbuild@kujilabo.com"
        git config --global user.name "cloudbuild"

  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "--recurse-submodules", "git@github.com:kujilabo/kujilabo-manifests.git"]
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["checkout", "master"]

  # - name: "gcr.io/cloud-builders/git"
  #   entrypoint: "bash"
  #   args:
  #     - -c
  #     - |
  #       ls

  # synthesizer
  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests/cocotola-synthesizer-api/overlays/production"
    entrypoint: "bash"
    args:
      - -c
      - |
        ls

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/cocotola-synthesizer-api/overlays/production"
    args: ["edit", "set", "image", "gcr.io/cocotola/cocotola-synthesizer-api=gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA"]
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=cocotola-001", "GCLOUD_PROJECT=cocotola-001"]

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/cocotola-synthesizer-api/overlays/development"
    args: ["edit", "set", "image", "gcr.io/cocotola/cocotola-synthesizer-api=gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA"]
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=cocotola-001", "GCLOUD_PROJECT=cocotola-001"]

  # translator
  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests/cocotola-translator-api/overlays/production"
    entrypoint: "bash"
    args:
      - -c
      - |
        ls

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/cocotola-translator-api/overlays/production"
    args: ["edit", "set", "image", "gcr.io/cocotola/cocotola-translator-api=gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA"]
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=cocotola-001", "GCLOUD_PROJECT=cocotola-001"]

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/cocotola-translator-api/overlays/development"
    args: ["edit", "set", "image", "gcr.io/cocotola/cocotola-translator-api=gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA"]
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=cocotola-001", "GCLOUD_PROJECT=cocotola-001"]

  # tatoeba
  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests/cocotola-tatoeba-api/overlays/production"
    entrypoint: "bash"
    args:
      - -c
      - |
        ls

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/cocotola-tatoeba-api/overlays/production"
    args: ["edit", "set", "image", "gcr.io/cocotola/cocotola-tatoeba-api=gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA"]
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=cocotola-001", "GCLOUD_PROJECT=cocotola-001"]

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/cocotola-tatoeba-api/overlays/development"
    args: ["edit", "set", "image", "gcr.io/cocotola/cocotola-tatoeba-api=gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA"]
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=cocotola-001", "GCLOUD_PROJECT=cocotola-001"]

  # cocotola
  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests/cocotola-api/overlays/production"
    entrypoint: "bash"
    args:
      - -c
      - |
        ls

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/cocotola-api/overlays/production"
    args: ["edit", "set", "image", "gcr.io/cocotola/cocotola-api=gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA"]
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=cocotola-001", "GCLOUD_PROJECT=cocotola-001"]

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/cocotola-api/overlays/development"
    args: ["edit", "set", "image", "gcr.io/cocotola/cocotola-api=gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA"]
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=cocotola-001", "GCLOUD_PROJECT=cocotola-001"]

  # common
  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["diff"]

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["add", "."]

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["commit", "-m", "Update $SHORT_SHA"]

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["push", "origin", "master"]
    volumes:
      - name: "ssh"
        path: /root/.ssh

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_deploy_key/versions/latest
      env: "SSH_KEY"

images:
  - "gcr.io/$PROJECT_ID/cocotola-synthesizer-api"
  - "gcr.io/$PROJECT_ID/cocotola-translator-api"
  - "gcr.io/$PROJECT_ID/cocotola-tatoeba-api"
  - "gcr.io/$PROJECT_ID/cocotola-api"
