---
steps:
  # - name: 'gcr.io/cloud-builders/bazel'
  #   entrypoint: 'bazel'
  #   args: ['version']
  # - name: 'gcr.io/cloud-builders/bazel'
  #   entrypoint: 'bazel'
  #   args: ['build', '//...']

  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - -c
      - |
        git fetch --depth=2
        git diff --name-only HEAD^ HEAD | grep cocotola-api
        diff_cocotola=$?
        echo "$diff_cocotola" > /workspace/diff_cocotola.txt
        git diff --name-only HEAD^ HEAD | grep cocotola-translator-api
        diff_translator=$?
        echo "$diff_translator" > /workspace/diff_translator.txt
        git diff --name-only HEAD^ HEAD | grep cocotola-synthesizer-api
        diff_synthesizer=$?
        echo "$diff_synthesizer" > /workspace/diff_synthesizer.txt
        git diff --name-only HEAD^ HEAD | grep cocotola-tatoeba-api
        diff_tatoeba=$?
        echo "$diff_tatoeba" > /workspace/diff_tatoeba.txt
        git diff --name-only HEAD^ HEAD | grep cocotola-web
        diff_web=$?
        echo "$diff_web" > /workspace/diff_web.txt
    env:
      - diff_cocotola=$diff_cocotola

  # synthesizer
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/cocotola-synthesizer-api:latest || exit 0"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        diff_synthesizer=$(cat /workspace/diff_synthesizer.txt)
        if [ $diff_synthesizer == '0' ]; then docker build -t gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA --cache-from gcr.io/$PROJECT_ID/cocotola-synthesizer-api:latest ./cocotola-synthesizer-api; fi
        if [ $diff_synthesizer == '0' ]; then docker tag gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA gcr.io/$PROJECT_ID/cocotola-synthesizer-api:latest; fi
        if [ $diff_synthesizer == '0' ]; then docker push gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA; fi

  # translator
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/cocotola-translator-api:latest || exit 0"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        diff_translator=$(cat /workspace/diff_translator.txt)
        if [ $diff_translator == '0' ]; then docker build -t gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA --cache-from gcr.io/$PROJECT_ID/cocotola-translator-api:latest ./cocotola-translator-api; fi
        if [ $diff_translator == '0' ]; then docker tag gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA gcr.io/$PROJECT_ID/cocotola-translator-api:latest; fi
        if [ $diff_translator == '0' ]; then docker push gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA; fi

  # tatoeba
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/cocotola-tatoeba-api:latest || exit 0"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        diff_tatoeba=$(cat /workspace/diff_tatoeba.txt)
        if [ $diff_tatoeba == '0' ]; then docker build -t gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA --cache-from gcr.io/$PROJECT_ID/cocotola-tatoeba-api:latest ./cocotola-tatoeba-api; fi
        if [ $diff_tatoeba == '0' ]; then docker tag gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA gcr.io/$PROJECT_ID/cocotola-tatoeba-api:latest; fi
        if [ $diff_tatoeba == '0' ]; then docker push gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA; fi
        if [ $diff_tatoeba == '0' ]; then docker push gcr.io/$PROJECT_ID/cocotola-tatoeba-api:latest; fi

  # cocotola
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        diff_cocotola=$(cat /workspace/diff_cocotola.txt)
        if [ $diff_cocotola == '0' ]; then docker pull     gcr.io/$PROJECT_ID/cocotola-api-builder:latest || exit 0; fi
        if [ $diff_cocotola == '0' ]; then docker build -t gcr.io/$PROJECT_ID/cocotola-api-builder:latest --target builder ./cocotola-api; fi
        if [ $diff_cocotola == '0' ]; then docker push     gcr.io/$PROJECT_ID/cocotola-api-builder:latest; fi

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        diff_cocotola=$(cat /workspace/diff_cocotola.txt)
        if [ $diff_cocotola == '0' ]; then docker pull gcr.io/$PROJECT_ID/cocotola-api:latest || exit 0; fi
        if [ $diff_cocotola == '0' ]; then docker build -t gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA --cache-from gcr.io/$PROJECT_ID/cocotola-api-builder:latest --cache-from gcr.io/$PROJECT_ID/cocotola-api:latest ./cocotola-api; fi
        if [ $diff_cocotola == '0' ]; then docker tag gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA gcr.io/$PROJECT_ID/cocotola-api:latest; fi
        if [ $diff_cocotola == '0' ]; then docker push gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA; fi
        if [ $diff_cocotola == '0' ]; then docker push gcr.io/$PROJECT_ID/cocotola-api:latest; fi

  # web
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/cocotola-web:latest || exit 0"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        diff_web=$(cat /workspace/diff_web.txt)
        if [ $diff_web == '0' ]; then docker build -t gcr.io/$PROJECT_ID/cocotola-web:$SHORT_SHA --cache-from gcr.io/$PROJECT_ID/cocotola-web:latest ./cocotola-web; fi
        if [ $diff_web == '0' ]; then docker tag gcr.io/$PROJECT_ID/cocotola-web:$SHORT_SHA gcr.io/$PROJECT_ID/cocotola-web:latest; fi
        if [ $diff_web == '0' ]; then docker push gcr.io/$PROJECT_ID/cocotola-web:$SHORT_SHA; fi

  # common
  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - -c
      - |
        git config --global user.email "cloudbuild@kujilabo.com"
        git config --global user.name "cloudbuild"

  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "--recurse-submodules", "git@github.com:kujilabo/kujilabo-manifests.git"]
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["checkout", "master"]

  # synthesizer
  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-synthesizer-api/overlays/production"
    args:
      - -c
      - |
        diff_synthesizer=$(cat /workspace/diff_synthesizer.txt)
        if [ $diff_synthesizer == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-synthesizer-api=gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-synthesizer-api/overlays/development"
    args:
      - -c
      - |
        diff_synthesizer=$(cat /workspace/diff_synthesizer.txt)
        if [ $diff_synthesizer == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-synthesizer-api=gcr.io/$PROJECT_ID/cocotola-synthesizer-api:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  # translator
  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-translator-api/overlays/production"
    args:
      - -c
      - |
        diff_translator=$(cat /workspace/diff_translator.txt)
        if [ $diff_translator == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-translator-api=gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-translator-api/overlays/development"
    args:
      - -c
      - |
        diff_translator=$(cat /workspace/diff_translator.txt)
        if [ $diff_translator == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-translator-api=gcr.io/$PROJECT_ID/cocotola-translator-api:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  # tatoeba
  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-tatoeba-api/overlays/production"
    args:
      - -c
      - |
        diff_tatoeba=$(cat /workspace/diff_tatoeba.txt)
        if [ $diff_tatoeba == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-tatoeba-api=gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-tatoeba-api/overlays/development"
    args:
      - -c
      - |
        diff_tatoeba=$(cat /workspace/diff_tatoeba.txt)
        if [ $diff_tatoeba == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-tatoeba-api=gcr.io/$PROJECT_ID/cocotola-tatoeba-api:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  # cocotola
  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-api/overlays/production"
    args:
      - -c
      - |
        diff_cocotola=$(cat /workspace/diff_cocotola.txt)
        if [ $diff_cocotola == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-api=gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-api/overlays/development"
    args:
      - -c
      - |
        diff_cocotola=$(cat /workspace/diff_cocotola.txt)
        if [ $diff_cocotola == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-api=gcr.io/$PROJECT_ID/cocotola-api:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  # web
  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-web/overlays/production"
    args:
      - -c
      - |
        diff_web=$(cat /workspace/diff_web.txt)
        if [ $diff_web == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-web=gcr.io/$PROJECT_ID/cocotola-web:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  - name: "gcr.io/$PROJECT_ID/kustomize"
    entrypoint: "bash"
    dir: "kujilabo-manifests/cocotola-web/overlays/development"
    args:
      - -c
      - |
        diff_web=$(cat /workspace/diff_web.txt)
        if [ $diff_web == '0' ]; then kustomize edit set image gcr.io/cocotola/cocotola-web=gcr.io/$PROJECT_ID/cocotola-web:$SHORT_SHA; fi
    env: ["APPLY=false", "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-c", "CLOUDSDK_CONTAINER_CLUSTER=$PROJECT_ID", "GCLOUD_PROJECT=$PROJECT_ID"]

  # common
  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["diff"]

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["add", "."]

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["commit", "-m", "Update $SHORT_SHA"]

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args: ["push", "origin", "master"]
    volumes:
      - name: "ssh"
        path: /root/.ssh

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_deploy_key/versions/latest
      env: "SSH_KEY"

images:
  - "gcr.io/$PROJECT_ID/cocotola-synthesizer-api:latest"
  - "gcr.io/$PROJECT_ID/cocotola-translator-api:latest"
  - "gcr.io/$PROJECT_ID/cocotola-tatoeba-api:latest"
  - "gcr.io/$PROJECT_ID/cocotola-api:latest"
