---
steps:
  - name: 'gcr.io/cloud-builders/bazel'
    entrypoint: 'bazel'
    args: ['version']
  - name: 'gcr.io/cloud-builders/bazel'
    entrypoint: 'bazel'
    args: ['build', '//...']

#   - name: "gcr.io/cloud-builders/docker"
#     id: "docker build"
#     args:
#       - "build"
#       - "-t"
#       - "gcr.io/$PROJECT_ID/cocotola-translator-api-2:$SHORT_SHA"
#       - "./cocotola-translator-api"

#   - name: "gcr.io/cloud-builders/docker"
#     id: "docker tag"
#     args:
#       - "tag"
#       - "gcr.io/$PROJECT_ID/cocotola-translator-api-2:$SHORT_SHA"
#       - "gcr.io/$PROJECT_ID/cocotola-translator-api-2:latest"

#   - name: "gcr.io/cloud-builders/docker"
#     id: "docker push"
#     args:
#       - "push"
#       - "gcr.io/$PROJECT_ID/cocotola-translator-api-2:$SHORT_SHA"

# availableSecrets:
#   secretManager:
#     - versionName: projects/$PROJECT_ID/secrets/github_deploy_key/versions/latest
#       env: "SSH_KEY"

# images:
#   - "gcr.io/$PROJECT_ID/cocotola-translator-api"
