// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/kujilabo/cocotola/cocotola-api/src/app/domain"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Audio is an autogenerated mock type for the Audio type
type Audio struct {
	mock.Mock
}

// GetAudioModel provides a mock function with given fields:
func (_m *Audio) GetAudioModel() domain.AudioModel {
	ret := _m.Called()

	var r0 domain.AudioModel
	if rf, ok := ret.Get(0).(func() domain.AudioModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AudioModel)
		}
	}

	return r0
}

// NewAudio creates a new instance of Audio. It also registers a cleanup function to assert the mocks expectations.
func NewAudio(t testing.TB) *Audio {
	mock := &Audio{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
