// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	appdomain "github.com/kujilabo/cocotola/cocotola-api/src/app/domain"

	domain "github.com/kujilabo/cocotola/cocotola-api/src/user/domain"

	mock "github.com/stretchr/testify/mock"

	service "github.com/kujilabo/cocotola/cocotola-api/src/app/service"

	testing "testing"

	time "time"
)

// StudyRecordRepository is an autogenerated mock type for the StudyRecordRepository type
type StudyRecordRepository struct {
	mock.Mock
}

// AddRecord provides a mock function with given fields: ctx, operator, appUserID, workbookID, problemTypeID, studyTypeID, problemID, mastered
func (_m *StudyRecordRepository) AddRecord(ctx context.Context, operator domain.SystemOwnerModel, appUserID domain.AppUserID, workbookID appdomain.WorkbookID, problemTypeID uint, studyTypeID uint, problemID appdomain.ProblemID, mastered bool) error {
	ret := _m.Called(ctx, operator, appUserID, workbookID, problemTypeID, studyTypeID, problemID, mastered)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SystemOwnerModel, domain.AppUserID, appdomain.WorkbookID, uint, uint, appdomain.ProblemID, bool) error); ok {
		r0 = rf(ctx, operator, appUserID, workbookID, problemTypeID, studyTypeID, problemID, mastered)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountAnsweredProblems provides a mock function with given fields: ctx, targetUserID, targetDate
func (_m *StudyRecordRepository) CountAnsweredProblems(ctx context.Context, targetUserID domain.AppUserID, targetDate time.Time) (*service.CountAnsweredResults, error) {
	ret := _m.Called(ctx, targetUserID, targetDate)

	var r0 *service.CountAnsweredResults
	if rf, ok := ret.Get(0).(func(context.Context, domain.AppUserID, time.Time) *service.CountAnsweredResults); ok {
		r0 = rf(ctx, targetUserID, targetDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CountAnsweredResults)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.AppUserID, time.Time) error); ok {
		r1 = rf(ctx, targetUserID, targetDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStudyRecordRepository creates a new instance of StudyRecordRepository. It also registers a cleanup function to assert the mocks expectations.
func NewStudyRecordRepository(t testing.TB) *StudyRecordRepository {
	mock := &StudyRecordRepository{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
