// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/kujilabo/cocotola/cocotola-api/src/job/service"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// JobHistoryRepository is an autogenerated mock type for the JobHistoryRepository type
type JobHistoryRepository struct {
	mock.Mock
}

// AddJobHistory provides a mock function with given fields: ctx, jobHistory
func (_m *JobHistoryRepository) AddJobHistory(ctx context.Context, jobHistory service.JobHistory) error {
	ret := _m.Called(ctx, jobHistory)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.JobHistory) error); ok {
		r0 = rf(ctx, jobHistory)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJobHistoryRepository creates a new instance of JobHistoryRepository. It also registers a cleanup function to assert the mocks expectations.
func NewJobHistoryRepository(t testing.TB) *JobHistoryRepository {
	mock := &JobHistoryRepository{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
