---
on: [pull_request]
name: Test
jobs:
  test_go:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
        workdir:
          - lib
          - cocotola-api
          - cocotola-synthesizer-api
          - cocotola-translator-api
          - cocotola-tatoeba-api
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3307
          mysql version: "5.7"
          mysql database: "testdb"
          mysql user: "user"
          mysql password: "password"
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3317
          mysql version: "5.7"
          mysql database: "testdb"
          mysql user: "user"
          mysql password: "password"
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3327
          mysql version: "5.7"
          mysql database: "testdb"
          mysql user: "user"
          mysql password: "password"
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3337
          mysql version: "5.7"
          mysql database: "testdb"
          mysql user: "user"
          mysql password: "password"
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Setup Bazelisk
      #   uses: bazelbuild/setup-bazelisk@v2.0.0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            cocotola-api/**

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Check diff
        if: startsWith(steps.changed-files.outputs.all_changed_files, 'cocotola-api')
        run: echo DIFF
      # - uses: technote-space/get-diff-action@v6
      #   with:
      #     PATTERNS: |
      #       "**/**.md"
      # - name: Test
      #   # if: (env.GIT_DIFF | grep ${{ matrix.workdir }}) 0
      #   run: |
      #     echo ${{env.GIT_DIFF}}
      #     echo ${{env.GIT_DIFF}} | grep ${{ matrix.workdir }}
      #     diff=$(echo ${{env.GIT_DIFF}} | grep ${{ matrix.workdir }})
      #     echo ${{diff}}
        # working-directory: ${{ matrix.workdir }}
      # - name: Test
      #   working-directory: ${{ matrix.workdir }}
      #   run: go test -coverprofile="coverage.txt" -covermode=atomic ./...
      # - name: Coverage
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ${{ matrix.workdir }}/coverage.txt
      #     flags: ${{ matrix.workdir }}
